// <auto-generated />
using ECommerce.Services.ProdictAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerce.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119185712_SeedProductsUpdate")]
    partial class SeedProductsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "A refreshing mix of chopped tomatoes, cucumbers, onions, peppers, and grated sirene (white brine cheese), named after the Shops region.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Shopska Salad",
                            Price = 11.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "Traditional Bulgarian salad, which is made of strained yogurt, cucumber, garlic, salt, usually cooking oil, dill, sometimes roasted peppers, walnuts and parsley.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Snezhanka salad",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Pastry consisting of thin sheets of dough that are filled with grated pumpkin, coarsely ground walnuts, sugar, and cinnamon.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Tikvenik ",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Main",
                            Description = "Kavarma is a hearty, slow-cooked stew from Bulgarian cuisine, typically made with chunks of pork, chicken, or beef, simmered with vegetables like onions, peppers, tomatoes, and mushrooms, often in a traditional clay pot (gyuveche) with spices like paprika and savory (chubritsa), resulting in a rich, flavorful main course, sometimes finished with an egg. ",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Kavarma ",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
